In [1]:
%load_ext autoreload
%autoreload 2

## Initial Eda

Vamos a crear un eda inicial para ambos datasets para definir cuál de los dos debería elegir.

importamos la las librerias necesarias y los modulos internos

In [16]:
import pandas as pd
import io
from data_observatory_test_062025.config import RAW_DATA_DIR
from data_observatory_test_062025.generic_eda_report import generic_report

In [3]:
RAW_DATA_DIR

PosixPath('/var/home/felipecabello/git/data_observatory_test_062025/data/raw')

Cargamos los datos a un dataframe

In [4]:
datasets = [dataset for dataset in RAW_DATA_DIR.rglob("*.csv") if dataset.is_file()]

In [17]:
datasets

[PosixPath('/var/home/felipecabello/git/data_observatory_test_062025/data/raw/datos_viviendas_censo.csv'),
 PosixPath('/var/home/felipecabello/git/data_observatory_test_062025/data/raw/datos_salud_individual.csv')]

In [6]:
pandas_dataframes = [pd.read_csv(dataset) for dataset in datasets]

In [7]:
df_viviendas = pandas_dataframes[0]
df_salud = pandas_dataframes[1]

Hacemos el reporte de vivienda

In [13]:
generic_report(df_viviendas)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31660 entries, 0 to 31659
Data columns (total 26 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_vivienda            31660 non-null  object
 1   comuna                 31660 non-null  object
 2   tipo_vivienda          31660 non-null  object
 3   num_dormitorios        31660 non-null  int64
 4   num_banos              31660 non-null  int64
 5   superficie_m2          31660 non-null  float64
 6   ano_construccion       31660 non-null  int64
 7   material_paredes       31660 non-null  object
 8   material_techo         31660 non-null  object
 9   num_personas_hogar     31660 non-null  int64
 10  num_hombres            31660 non-null  int64
 11  num_mujeres            31660 non-null  int64
 12  num_menores_18         31660 non-null  int64
 13  num_adultos_18_64      31660 non-null  int64
 14  num_adultos_65_plus    31660 non-null  int64
 15  ingreso_mensual_hogar  31660 non-null  int64
 16  jefe_hogar_edad        31660 non-null  int64
 17  jefe_hogar_sexo        31660 non-null  object
 18  jefe_hogar_educacion   31660 non-null  object
 19  agua_potable           31660 non-null  object
 20  electricidad           31660 non-null  object
 21  gas_natural            31660 non-null  object
 22  internet               31660 non-null  object
 23  telefono_fijo          31660 non-null  object
 24  vehiculo_propio        31660 non-null  object
 25  tenencia_vivienda      31660 non-null  object
dtypes: float64(1), int64(11), object(14)
memory usage: 6.3+ MB

==================== 1.1.1 Exploración Inicial ====================

--- Dataset shape ---
(31660, 26)

--- Dataset columns ---
Index(['id_vivienda', 'comuna', 'tipo_vivienda', 'num_dormitorios',
       'num_banos', 'superficie_m2', 'ano_construccion', 'material_paredes',
       'material_techo', 'num_personas_hogar', 'num_hombres', 'num_mujeres',
       'num_menores_18', 'num_adultos_18_64', 'num_adultos_65_plus',
       'ingreso_mensual_hogar', 'jefe_hogar_edad', 'jefe_hogar_sexo',
       'jefe_hogar_educacion', 'agua_potable', 'electricidad', 'gas_natural',
       'internet', 'telefono_fijo', 'vehiculo_propio', 'tenencia_vivienda'],
      dtype='object')

--- Dataset Info ---
None

--- Dtypes ---
id_vivienda               object
comuna                    object
tipo_vivienda             object
num_dormitorios            int64
num_banos                  int64
superficie_m2            float64
ano_construccion           int64
material_paredes          object
material_techo            object
num_personas_hogar         int64
num_hombres                int64
num_mujeres                int64
num_menores_18             int64
num_adultos_18_64          int64
num_adultos_65_plus        int64
ingreso_mensual_hogar      int64
jefe_hogar_edad            int64
jefe_hogar_sexo           object
jefe_hogar_educacion      object
agua_potable              object
electricidad              object
gas_natural               object
internet                  object
telefono_fijo             object
vehiculo_propio           object
tenencia_vivienda         object
dtype: object

--- Numeric Describe ---
       num_dormitorios     num_banos  superficie_m2  ano_construccion  \
count     31660.000000  31660.000000    31660.00000      31660.000000
mean          3.003253      2.008402      114.30855       1986.597789
std           1.413193      0.813314       49.05255         21.369746
min           1.000000      1.000000       30.00000       1950.000000
25%           2.000000      1.000000       71.70000       1968.000000
50%           3.000000      2.000000      113.50000       1987.000000
75%           4.000000      3.000000      156.80000       2005.000000
max           5.000000      3.000000      200.00000       2023.000000

       num_personas_hogar   num_hombres   num_mujeres  num_menores_18  \
count        31660.000000  31660.000000  31660.000000    31660.000000
mean             6.700095      3.341725      3.358370        1.659097
std              4.913740      3.588203      3.598514        1.358317
min              1.000000      0.000000      0.000000        0.000000
25%              3.000000      1.000000      1.000000        0.000000
50%              5.000000      2.000000      2.000000        1.000000
75%             10.000000      5.000000      5.000000        3.000000
max             20.000000     20.000000     20.000000        4.000000

       num_adultos_18_64  num_adultos_65_plus  ingreso_mensual_hogar  \
count       31660.000000         31660.000000           3.166000e+04
mean            2.542419             2.498579           1.650258e+06
std             3.259791             3.209771           7.822470e+05
min             0.000000             0.000000           3.000390e+05
25%             0.000000             0.000000           9.665070e+05
50%             1.000000             1.000000           1.654022e+06
75%             4.000000             4.000000           2.331099e+06
max            20.000000            20.000000           2.999967e+06

       jefe_hogar_edad
count     31660.000000
mean         48.902021
std          18.180175
min          18.000000
25%          33.000000
50%          49.000000
75%          65.000000
max          80.000000

--- Object Describe ---
           id_vivienda    comuna tipo_vivienda material_paredes  \
count            31660     31660         31660            31660
unique           31660        57            11               10
top     VIV_001560_DUP  Santiago          Casa         Hormigón
freq                 1       810          7823             7666

       material_techo jefe_hogar_sexo jefe_hogar_educacion agua_potable  \
count           31660           31660                31660        31660
unique              8               2                    5            2
top             Tejas               F               Básica           No
freq             7724           15839                 6467        15994

       electricidad gas_natural internet telefono_fijo vehiculo_propio  \
count         31660       31660    31660         31660           31660
unique            2           2        2             2               2
top              No          Sí       Sí            No              Sí
freq          16124       16126    16232         15914           15848

       tenencia_vivienda
count              31660
unique                 4
top            Arrendada
freq                8027

--- Valores Faltantes ---
id_vivienda              0
comuna                   0
tipo_vivienda            0
num_dormitorios          0
num_banos                0
superficie_m2            0
ano_construccion         0
material_paredes         0
material_techo           0
num_personas_hogar       0
num_hombres              0
num_mujeres              0
num_menores_18           0
num_adultos_18_64        0
num_adultos_65_plus      0
ingreso_mensual_hogar    0
jefe_hogar_edad          0
jefe_hogar_sexo          0
jefe_hogar_educacion     0
agua_potable             0
electricidad             0
gas_natural              0
internet                 0
telefono_fijo            0
vehiculo_propio          0
tenencia_vivienda        0

--- Duplicados ---
Número de filas duplicadas: 0

--- Valores únicos ---
id_vivienda              31660
comuna                      57
tipo_vivienda               11
num_dormitorios              5
num_banos                    3
superficie_m2             1701
ano_construccion            74
material_paredes            10
material_techo               8
num_personas_hogar          20
num_hombres                 21
num_mujeres                 21
num_menores_18               5
num_adultos_18_64           21
num_adultos_65_plus         21
ingreso_mensual_hogar    31485
jefe_hogar_edad             63
jefe_hogar_sexo              2
jefe_hogar_educacion         5
agua_potable                 2
electricidad                 2
gas_natural                  2
internet                     2
telefono_fijo                2
vehiculo_propio              2
tenencia_vivienda            4
============================================================

In [14]:
generic_report(df_salud)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53039 entries, 0 to 53038
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_paciente            53039 non-null  object
 1   fecha_nacimiento       53039 non-null  object
 2   edad                   53039 non-null  int64
 3   sexo                   52217 non-null  object
 4   comuna_residencia      53039 non-null  object
 5   fecha_atencion         52698 non-null  object
 6   fecha_inicio_sintomas  52680 non-null  object
 7   codigo_enfermedad      52893 non-null  object
 8   diagnostico_principal  53039 non-null  object
 9   estado_salud           53039 non-null  object
 10  gravedad               53039 non-null  object
 11  peso_kg                53039 non-null  float64
 12  altura_mt              53039 non-null  float64
 13  presion_arterial       53039 non-null  object
 14  temperatura_corporal   53039 non-null  float64
 15  centro_salud           53039 non-null  object
 16  observaciones          0 non-null      float64
dtypes: float64(4), int64(1), object(12)
memory usage: 6.9+ MB

==================== 1.1.1 Exploración Inicial ====================

--- Dataset shape ---
(53039, 17)

--- Dataset columns ---
Index(['id_paciente', 'fecha_nacimiento', 'edad', 'sexo', 'comuna_residencia',
       'fecha_atencion', 'fecha_inicio_sintomas', 'codigo_enfermedad',
       'diagnostico_principal', 'estado_salud', 'gravedad', 'peso_kg',
       'altura_mt', 'presion_arterial', 'temperatura_corporal', 'centro_salud',
       'observaciones'],
      dtype='object')

--- Dataset Info ---
None

--- Dtypes ---
id_paciente               object
fecha_nacimiento          object
edad                       int64
sexo                      object
comuna_residencia         object
fecha_atencion            object
fecha_inicio_sintomas     object
codigo_enfermedad         object
diagnostico_principal     object
estado_salud              object
gravedad                  object
peso_kg                  float64
altura_mt                float64
presion_arterial          object
temperatura_corporal     float64
centro_salud              object
observaciones            float64
dtype: object

--- Numeric Describe ---
               edad       peso_kg     altura_mt  temperatura_corporal  \
count  53039.000000  53039.000000  53039.000000          53039.000000
mean      56.134222     79.889174      1.699048             37.750970
std       82.644542     23.144823      0.173465              1.009483
min       -5.000000     40.000000      1.400000             36.000000
25%       24.000000     59.900000      1.550000             36.900000
50%       50.000000     79.800000      1.700000             37.800000
75%       76.000000     99.900000      1.850000             38.600000
max      999.000000    120.000000      2.000000             39.500000

       observaciones
count            0.0
mean             NaN
std              NaN
min              NaN
25%              NaN
50%              NaN
75%              NaN
max              NaN

--- Object Describe ---
       id_paciente fecha_nacimiento   sexo comuna_residencia fecha_atencion  \
count        53039            53039  52217             53039          52698
unique       53039              102      7                79           1030
top     PAC_053038          unknown      F          Santiago     2023-13-45
freq             1             1335  25264              1296            358

       fecha_inicio_sintomas codigo_enfermedad   diagnostico_principal  \
count                  52680             52893                   53039
unique                  1063                30                       5
top               2023-13-45             P59.9  Infección respiratoria
freq                     351              2490                   10680

         estado_salud gravedad presion_arterial       centro_salud
count           53039    53039            53039              53039
unique              4        3             5551                  4
top     Recuperándose     Leve           173/82  Hospital Regional
freq            16150    20745               24              13390

--- Valores Faltantes ---
id_paciente                  0
fecha_nacimiento             0
edad                         0
sexo                       822
comuna_residencia            0
fecha_atencion             341
fecha_inicio_sintomas      359
codigo_enfermedad          146
diagnostico_principal        0
estado_salud                 0
gravedad                     0
peso_kg                      0
altura_mt                    0
presion_arterial             0
temperatura_corporal         0
centro_salud                 0
observaciones            53039

--- Duplicados ---
Número de filas duplicadas: 0

--- Valores únicos ---
id_paciente              53039
fecha_nacimiento           102
edad                       105
sexo                         7
comuna_residencia           79
fecha_atencion            1030
fecha_inicio_sintomas     1063
codigo_enfermedad           30
diagnostico_principal        5
estado_salud                 4
gravedad                     3
peso_kg                    801
altura_mt                   61
presion_arterial          5551
temperatura_corporal        36
centro_salud                 4
observaciones                0
============================================================

## Ambos datasets tiene sus desafios
Me parece que me iré por el de vivienda